### ISSUE TITLE
Make style consistent with main site

### ISSUE THREAD

**Issue by joehand** [datproject/docs#13]
Style should be consistent with [main site](http://dat-data.com/). Maybe should have same navigation header too?

This is dependent on [custom themes](https://github.com/freeman-lab/minidocs/issues/43) in minidocs.

**Comment by Kriesse** [comment]
Agreed! Waiting on https://github.com/datproject/docs/pull/16 to be merged in.

**Comment by Kriesse** [comment]
Added custom styles here: https://github.com/datproject/docs/pull/16/commits/05bd0943f615543ea3b277ec5f10197f9dc2b605

Minidocs prepends custom CSS, instead of adding it after the default CSS. Because of this, the namespacing is needed to increase specificity, and override default styles. Couldn't figure out why that is or how to change it, [filed an issue](https://github.com/freeman-lab/minidocs/issues/62).

It’s a bit ugly – but for now it gets the job done and makes the docs look slightly more consistent with the main site.

**Comment by joehand** [comment]
Cool! I'll take a look. There talk to add custom themes to minidocs, so that may be better when it is implemented.

**Comment by karissa** [comment]
A+

**Comment by joehand** [comment]
@Kriesse I hacked minidocs to make it more consistent, check it out https://docs.datproject.org/. Hopefully it is also consistent with your thoughts on the design. Let me know if I got it wrong anywhere =). Unfortunately, it may not be clear where to fix something because how I did the fork.
