### ISSUE TITLE
Restructure TOC and current content

### ISSUE THREAD

**Issue by clkao** [datproject/docs#9]

**Comment by joehand** [comment]
IRC Talk about this:

```

12:56 PM <jhand> karissa: i started to re-write the DIY dat page but maybe I'd be good to just have a whole cookbook type section
12:56 PM <•karissa> jhand: yeah!
12:56 PM <•karissa> jhand: diy dat is cool but it seems like maybe one of the many things you can do
12:56 PM <jhand> karissa: right. 
12:57 PM <•karissa> jhand: we also get a lot of questions. its almost like a FAQ could be useful and double as a cookbook too
12:57 PM <jhand> karissa: was there anything else you were thinking on the docs? i can spend this afternoon cleaning it up a bit
12:58 PM <•karissa> jhand: a long walkthrough example with a real dataset could be cool, like this is what happens when you do this, vs. that
```

**Comment by joehand** [comment]
Started work on this in https://github.com/datproject/docs/tree/update-content-toc. That branch depends on PR #12

**Comment by karissa** [comment]
I have started this on the simplify-tree branch

**Comment by joehand** [comment]
Cool, I can start to consolidate and merge some content into the simplify-tree branch. I like the cookbook section idea!

I am wary of having the maxogden/dat readme as the main landing page. It seems like the goals of the two pages are pretty different. A user that goes to the docs landing page may be trying to learn about what Dat is & could be used for. A user on the dat readme will want to install & use the CLI (assuming they are familiar with Dat). Right now the dat readme is kind of pulling double duty and I'd like to move away from that.

What is the goal of the first section? The "how dat works" page seems a bit technical to have as the second link. I started to write a [CLI tutorial](https://github.com/datproject/docs/blob/update-content-toc/docs/dat-cli.md) but not sure if that'd be a "cookbook" or something in the first section.

**Comment by karissa** [comment]
Yeah, it's a good idea to step back and think about the goal of the first section...

I love the CLI tutorial. I like how https://github.com/yoshuawuyts/choo is a reamde with a bunch of really big links for the key larger pointers (handbook, ecosystem, etc) and then followed by a long readme with an example. If your CLI tutorial is going to be more of a 'handbook' then let's link to it very big on the readme in the first section along with some other big links. With the current size it is, though, it might just be better as one of the first things the user sees when they come to the page. People are used to scrolling down pages, and I am not sure if they'll necessarily be looking at the links.

One of the things I liked about readthedocs is that it would surface subheadings on the left side, so you could have a 'user guide' or 'cli docs tutorial' in the welcome page/readme and a person could scroll down and find that or click on the left with a subheading. Not saying we should modify minidocs to do this, necessarily, but it is something to think about

I think that right now our users seem pretty technical.. and it could be easier to consolidate the two pages into one page instead of having two pages because we don't have that much content right now for a 'landing page for trying to learn about what Dat is & could be used for' and it would be easier to maintain. That was the idea around keeping the readme/welcome page the same.

**Comment by joehand** [comment]
Published updated TOC and content to http://docs.dat-data.com/. 

Still could use the RTD-like TOC on the sidebar ([minidocs issue to follow](https://github.com/freeman-lab/minidocs/issues/63)).
